### ISSUE TITLE
Remove non-open source software

### ISSUE THREAD

**Issue by MrKrisKrisu** [Traewelling/help-pages#1]
I would show only those apps on the third-party app page that provide their code as open source.
For example I would remove `Träwel Checkin for iOS` and `Inofficial-Traewelling Maps`.
There are no reasons to keep software private in our environment. We should use it to promote the open source idea.

https://github.com/Traewelling/help-pages/blob/8dfdd038bedbee7cc686d70f6e9f7d5136eaebd6/content/community/list%20of%20third%20party%20apps.md?plain=1#L30

https://github.com/Traewelling/help-pages/blob/8dfdd038bedbee7cc686d70f6e9f7d5136eaebd6/content/community/list%20of%20third%20party%20apps.md?plain=1#L22

**Comment by HerrLevin** [comment]
https://github.com/Traewelling/help-pages/commit/523a44fa61b40ed0d804055baf447da82a0c6313
